# Generated by Django 4.2.5 on 2023-09-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='variations',
            field=models.ManyToManyField(related_name='product_lines', through='product.ProductLineVariation', to='product.variation'),
        ),
        migrations.AlterUniqueTogether(
            name='productlinevariation',
            unique_together={('variation', 'product_line')},
        ),
    ]
