# Generated by Django 4.2.5 on 2023-09-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productlinevariation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='attributes', to='product.category'),
        ),
        migrations.AlterUniqueTogether(
            name='productlinevariation',
            unique_together={('variation', 'product_line')},
        ),
    ]
