# Generated by Django 4.2.4 on 2023-09-13 05:09

from django.db import migrations
import product.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='ordering',
            field=product.fields.OrderField(blank=True, null=True),
        ),
    ]
