# Generated by Django 4.2.5 on 2023-09-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_attribute_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='product.category'),
        ),
    ]
