# Generated by Django 4.2.5 on 2023-10-01 12:48

from django.db import migrations
import product.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=product.fields.SlugUniqueToField(blank=True, max_length=255, null=True),
        ),
    ]
