# Generated by Django 4.2.5 on 2023-10-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_brand_slug_alter_brand_name_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='categories', to='product.attribute'),
        ),
        migrations.AddField(
            model_name='productline',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
