# Generated by Django 4.2.5 on 2023-09-23 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='variation',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.attribute'),
        ),
        migrations.CreateModel(
            name='ProductLineVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_line_variations', to='product.productline')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_line_variations', to='product.variation')),
            ],
        ),
        migrations.AddField(
            model_name='productline',
            name='variations',
            field=models.ManyToManyField(through='product.ProductLineVariation', to='product.variation'),
        ),
    ]
